// Central route aggregator — mounts all API routes under /api
const express = require('express')
const authRoutes = require('./authRoutes')
const userRoutes = require('./userRoutes')
const categoryRoutes = require('./categoryRoutes')
const productRoutes = require('./productRoutes')
const floorRoutes = require('./floorRoutes')
const paymentSettingsRoutes = require('./paymentSettingsRoutes')
const couponRoutes = require('./couponRoutes')
const promotionRoutes = require('./promotionRoutes')
const customerRoutes = require('./customerRoutes')
const bookingRoutes = require('./bookingRoutes')
const orderRoutes = require('./orderRoutes')
const sessionRoutes = require('./sessionRoutes')
const tableRoutes = require('./tableRoutes')
const reportRoutes = require('./reportRoutes')

const router = express.Router()

router.use('/auth', authRoutes)
router.use('/users', userRoutes)
router.use('/categories', categoryRoutes)
router.use('/products', productRoutes)
router.use('/floors', floorRoutes)
router.use('/tables', tableRoutes)
router.use('/payment-settings', paymentSettingsRoutes)
router.use('/coupons', couponRoutes)
router.use('/promotions', promotionRoutes)
router.use('/customers', customerRoutes)
router.use('/bookings', bookingRoutes)
router.use('/orders', orderRoutes)
router.use('/sessions', sessionRoutes)
router.use('/reports', reportRoutes)

module.exports = router
